// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoxhZYxDV-wmNWo6_TW8U6GpCrBFlNwE',
    appId: '1:274756380890:web:d3c94c515f8801ad0e5de3',
    messagingSenderId: '274756380890',
    projectId: 'how-much-crazyatom',
    authDomain: 'how-much-crazyatom.firebaseapp.com',
    storageBucket: 'how-much-crazyatom.firebasestorage.app',
    measurementId: 'G-PSJDTCSY65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANBeSP9JIpR83kNkQjrMZcGG0HwdkJAsM',
    appId: '1:274756380890:android:609203e031ab7fdd0e5de3',
    messagingSenderId: '274756380890',
    projectId: 'how-much-crazyatom',
    storageBucket: 'how-much-crazyatom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuyZFwCR8Mn66fBFVHLD1BcoY7WCd7uZQ',
    appId: '1:274756380890:ios:668b75ab28ccf8260e5de3',
    messagingSenderId: '274756380890',
    projectId: 'how-much-crazyatom',
    storageBucket: 'how-much-crazyatom.firebasestorage.app',
    iosBundleId: 'com.howmuch.crazyatom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuyZFwCR8Mn66fBFVHLD1BcoY7WCd7uZQ',
    appId: '1:274756380890:ios:668b75ab28ccf8260e5de3',
    messagingSenderId: '274756380890',
    projectId: 'how-much-crazyatom',
    storageBucket: 'how-much-crazyatom.firebasestorage.app',
    iosBundleId: 'com.howmuch.crazyatom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoxhZYxDV-wmNWo6_TW8U6GpCrBFlNwE',
    appId: '1:274756380890:web:5a0db7e251ad28d20e5de3',
    messagingSenderId: '274756380890',
    projectId: 'how-much-crazyatom',
    authDomain: 'how-much-crazyatom.firebaseapp.com',
    storageBucket: 'how-much-crazyatom.firebasestorage.app',
    measurementId: 'G-ZSSTLEE4PP',
  );

}